#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
from os.path import join as pjoin
from os.path import basename
import shutil
import time
import unittest

import trigtestutils as trigutil
import testutils as util
from testutils import print3

import dasherlib


class the_tests( trigutil.trigTestCase ):

    def setUp(self):
        ""
        trigutil.trigTestCase.setUp( self )
        self.webfile = None

    def setWebFile(self, filename):
        ""
        assert os.path.exists( filename )
        self.webfile = filename

    def tearDown(self):
        ""
        if '-i' in util.runoptions:
            import webbrowser
            if self.webfile:
                assert os.path.exists( self.webfile )
                webbrowser.open( self.webfile )
                raw_input( 'Press <Enter> to continue...' )
            elif os.path.exists( 'testpage.htm' ):
                webbrowser.open( 'testpage.htm' )
                raw_input( 'Press <Enter> to continue...' )

    def run_pass_fail_diff_tests(self, giturl, epoch):
        ""
        util.writefile( 'passfaildiff.vvt', """
            #VVT: parameterize : res = pass fail diff
            import vvtest_util as vvt
            import script_util as util
            if vvt.res == 'fail':
                raise Exception( 'fake exception' )
            elif vvt.res == 'diff':
                util.exit_diff()
            """ )
        time.sleep(1)
        x,out = util.runcmd( trigutil.vvtest_file + \
                             ' -w -vv -n 4 --plat '+core_platform_name() + \
                             ' --gitlab '+giturl + \
                             ' --results-date '+str(epoch) )

    def make_dual_test_results(self):
        ""
        url = util.create_bare_repo_with_topic_branch( 'resrepo' )

        self.epoch1 = 1561499669.31  # Tue Jun 25 15:54:29 2019
        self.run_pass_fail_diff_tests( url, self.epoch1 )

        self.epoch2 = 1564480574.74  # Tue Jul 30 03:56:14 2019
        self.run_pass_fail_diff_tests( url, self.epoch2 )

        return url

    def test_reading_results(self):
        ""
        url = self.make_dual_test_results()

        dash = dasherlib.DashboardCreator( url )
        dash.readResults()

        dsL = dash.getDateStamps()
        dsL.sort()
        assert len( dsL ) == 2
        assert abs( dsL[0] - self.epoch1 ) < 70*60
        assert abs( dsL[1] - self.epoch2 ) < 70*60

    def test_formatting_elapsed_time(self):
        ""
        assert dasherlib.format_elapsed_time( 0 ) == '0:00'
        assert dasherlib.format_elapsed_time( 5 ) == '0:05'
        assert dasherlib.format_elapsed_time( 65 ) == '1:05'
        assert dasherlib.format_elapsed_time( 60 ) == '1:00'
        assert dasherlib.format_elapsed_time( 53*60+9 ) == '53:09'
        assert dasherlib.format_elapsed_time( 60*60 ) == '1:00:00'
        assert dasherlib.format_elapsed_time( 60*60+5 ) == '1:00:05'
        assert dasherlib.format_elapsed_time( 60*60+35 ) == '1:00:35'
        assert dasherlib.format_elapsed_time( 60*60+65 ) == '1:01:05'
        assert dasherlib.format_elapsed_time( 60*60+60*25 ) == '1:25:00'
        assert dasherlib.format_elapsed_time( 13*60*60+60*25 ) == '13:25:00'
        assert dasherlib.format_elapsed_time( 26*60*60+60*25+24 ) == '26:25:24'

    def test_writing_history_page(self):
        ""
        url = self.make_dual_test_results()

        dash = dasherlib.DashboardCreator( url )
        dash.readResults()
        dash.writeHistoryPage( 'testpage.htm' )

    def test_dasher_command_line_errors(self):
        ""
        x,out = util.runcmd( trigutil.dasher_file+' -h' )
        assert 'SYNOPSIS' in out

        x,out = util.runcmd( trigutil.dasher_file+' --help' )
        assert 'SYNOPSIS' in out

        x,out = util.runcmd( trigutil.dasher_file, raise_on_error=False )
        x != 0

        x,out = util.runcmd( trigutil.dasher_file+' foobar.htm',
                             raise_on_error=False )
        x != 0

    def test_running_dasher_application(self):
        ""
        os.mkdir( 'webpage1' )
        os.mkdir( 'webpage2' )

        url = self.make_dual_test_results()

        cmd = trigutil.dasher_file + ' --gitlab '+url + ' webpage1/page.htm'
        x,out = util.runcmd( cmd )

        assert os.path.isfile( 'webpage1/page.htm' )

        cmd = trigutil.dasher_file + ' --gitlab '+url + ' webpage2'
        x,out = util.runcmd( cmd )

        assert os.path.isfile( 'webpage2/index.htm' )
        self.setWebFile( 'webpage2/index.htm' )


def core_platform_name():
    ""
    if os.uname()[0].lower().startswith( 'darwin' ):
        return 'Darwin'
    else:
        return 'Linux'


if sys.version_info[0] > 2:
    raw_input = input


#######################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
