#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import unittest

import trigtestutils as trigutil
import testutils as util
from testutils import print3

# the module being tested
import kerberos

from command import Command

kerbfile = os.path.join( os.path.dirname(trigutil.testsrcdir), 'kerberos.py' )


######################################################################

class catchall( unittest.TestCase ):

    def setUp(self):
        ""
        util.setup_test()
        os.environ[ 'COMMAND_DRYRUN' ] = ''

    def test_set_ticket(self):
        """
        the set_ticket function sets the KRB5CCNAME environ variable
        """
        if 'KRB5CCNAME' in os.environ:
            os.environ.pop( 'KRB5CCNAME' )

        kerberos.set_ticket()

        assert 'KRB5CCNAME' in os.environ

    def test_init_ticket(self):
        ""
        kerberos.init_ticket( echo='none' )
        kerberos.init_ticket()

    def test_destroy_ticket(self):
        ""
        kerberos.destroy_ticket( echo='none' )
        kerberos.destroy_ticket()

    def test_renew_ticket(self):
        ""
        kerberos.renew_ticket( echo='none' )
        kerberos.renew_ticket()

    def test_man_page(self):
        ""
        os.environ.pop( 'COMMAND_DRYRUN' )
        Command( '$kerbfile -h' ).run( raise_on_error=True )
        Command( '$kerbfile --help' ).run( raise_on_error=True )


######################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
