#!/usr/bin/env python

import os, sys, re, string
import time

from testutils import *

mydir = get_test_dir()

vvtestdir = os.path.normpath( mydir + '/..' )
toolsdir = os.path.normpath( vvtestdir + '/..' )
xmlwrapperdir = os.path.normpath( mydir + '/../../makemflib' )

sys.path.insert( 0, xmlwrapperdir )
sys.path.insert( 0, vvtestdir )
import CommonSpec
import xmlwrapper
import cshScriptWriter
import TestSpecCreator

xreader = xmlwrapper.XmlDocReader()

xdb = CommonSpec.CommonSpecDB()
xdoc = xreader.readDoc( os.path.join(vvtestdir, 'exeDB.xml') )
CommonSpec.scanCommonSpecs( xdoc, xdb )

class FakePlatform:
    def __init__(self): pass
    def getName(self): return "fakeplatform"
    def getCompiler(self): return "fakecompiler"
    def getEnvironment(self):
        D = { 'ENVAR':'envarval' }
        return D

plat = FakePlatform()

if not os.path.exists('tdir'):
  os.mkdir( 'tdir' )
testdir = os.path.join( mydir, 'tdir' )

rmallfiles()

print "1111111111111111111111111111111111111"

fp = open('t1.xml',"w")
fp.writelines( [
     '<rtest name="atest">\n',
     '  <execute name="exename"> echo "hello world" </execute>\n',
     '</rtest>\n' ] )
fp.close()
xdoc = xreader.readDoc('t1.xml')
tL = TestSpecCreator.createTestObjects( xdoc, '.', 't1.xml' )
assert len(tL) == 1
cshScriptWriter.writeScript( tL[0], xdb, plat,
                             toolsdir, os.getcwd(), testdir,
                             [], [], 'runscript', 0 )
time.sleep(1)
assert os.path.exists('runscript')
fp = open( 'runscript', 'r' )
for line in fp.xreadlines():
  sys.stdout.write( line )
