#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3


class the_tests( vtu.vvtestTestCase ):

    def test_run_vvtest_on_a_file_in_the_current_directory(self):
        ""
        util.writefile( 'scr.vvt', """
            import os
            import vvtest_util as vvt
            import script_util as util
            fp = open( 'touchme', 'w' )
            fp.close()
            """ )
        time.sleep(1)

        cmd = vtu.vvtest_command_line( 'scr.vvt' )
        x,out = util.runcmd( cmd )

        # magic: not done
        # assert x == 0
        # assert os.path.isfile( 'touchme' )


questions = \
"""
    - vvt file in the current working dir
    - vvt file from another directory
    - more than one vvt file on the command line
    - mixing a directory and a vvt file on the command line
    - more than one test in the vvt file (a parameterized test)
"""

############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
