#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import unittest
import glob

import testutils as util
from testutils import print3


class inlining_results_file_includes( unittest.TestCase ):

    def setUp(self):
        util.setup_test()

    def test_restarting_a_killed_batch_run_three_times(self):
        """
        If a batch run is killed before the result file includes are inlined,
        the only record of the results exist in the batch directories.  But
        the batch directories are cleaned out before running the next time.
        This means that previous results will be lost if they are not inlined
        during vvtest startup.  This test checks that they are by restarting
        a killed batch run a few times in a row.
        """
        util.writefile( "lazyA.vvt", """
            import time
            time.sleep(1)
            fp = open( 'touchA.txt', 'w' ) ; fp.close()
            """ )
        util.writefile( "lazyB.vvt", """
            import time
            time.sleep(1)
            fp = open( 'touchB.txt', 'w' ) ; fp.close()
            """ )
        util.writefile( "lazyC.vvt", """
            import time
            time.sleep(1)
            fp = open( 'touchC.txt', 'w' ) ; fp.close()
            """ )
        time.sleep(1)

        opts = '--qsub-limit 1 --force'

        util.interrupt_vvtest_batch( '--qsub-limit 1',
                                     count=1, signum='SIGTERM' )
        time.sleep(1)

        # exactly one of the three tests should have completed
        assert len( util.findfiles( 'touch*.txt', 'TestResults*' ) ) == 1

        util.interrupt_vvtest_batch( '--qsub-limit 1 --force',
                                     count=1, signum='SIGTERM' )
        time.sleep(1)

        # exactly one more of the three tests should have completed
        assert len( util.findfiles( 'touch*.txt', 'TestResults*' ) ) == 2

        vrun = util.runvvtest( '--force', batch=True )
        time.sleep(1)

        # only the last of the three tests should have been run
        vrun.assertCounts( total=1, npass=1 )
        assert len( glob.glob( 'TestResults*/lazy*/touch*.txt' ) ) == 3

        # all three tests should show as completed
        util.runvvtest( '-i' ).assertCounts( total=3, npass=3 )

    def test_failed_batch_job_issues_warning_about_not_finishing(self):
        ""
        util.writefile( "sleeper1.xml", """
            <rtest name="sleeper1">
                <timeout value="15"/>
                <execute> sleep 5 </execute>
            </rtest>""" )
        util.writefile( "sleeper2.xml", """
            <rtest name="sleeper2">
                <timeout value="15"/>
                <execute> sleep 5 </execute>
            </rtest>""" )
        util.writefile( "sleeper3.xml", """
            <rtest name="sleeper3">
                <timeout value="15"/>
                <execute> sleep 5 </execute>
            </rtest>""" )
        util.writefile( "sleeper4.xml", """
            <rtest name="sleeper4">
                <timeout value="15"/>
                <execute> sleep 5 </execute>
            </rtest>""" )
        time.sleep(1)

        # these four tests are run in two batch
        # batch zero will be ok, while batch one will crash
        # this should cause batch one to show "did not seem to finish"

        opts = '--batch --qsub-limit 1 --qsub-length 40'
        xok,out = util.interrupt_vvtest_run( opts, count=1, qid=1 )

        L = util.grep( out, 'did not seem to finish:' )
        assert len(L) == 1
        L2 = L[0].split(':')[-1].split()  # qid list as strings
        L2 = [ int(s) for s in L2 ]  # make integer qids
        assert len(L2) == 1 and L2[0] == 1

        assert len( util.greptestlist( out, 'sleeper[1-4]' ) ) == 4
        assert len( util.greptestlist( out, 'sleeper[1-4] .*pass' ) ) == 3


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
