#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import unittest
import time
import glob

import testutils as util
from testutils import print3


class Testing_boostrap_file( unittest.TestCase ):

    def setUp(self):
        util.setup_test()

    def test_without_a_bootstrap_file(self):
        ""
        util.writefile( 'hello.py.vvt', """
            import os, sys
            print ( "hello from the python test script" )
            """ )
        time.sleep(1)

        ok,out = util.run_cmd( util.vvtest )
        assert ok
        assert util.numpass( out ) == 1

    def test_using_a_softlink_to_vvtest(self):
        ""
        util.writefile( 'hello.py.vvt', """
            import os, sys
            print ( "hello from the python test script" )
            """ )
        os.symlink( util.vvtest, 'vvtest' )
        time.sleep(1)

        ok,out = util.run_cmd( os.path.abspath( 'vvtest' ) )
        assert ok
        assert util.numpass( out ) == 1

    def test_with_a_bootstrap_file(self):
        ""
        util.writefile( 'hello.py.vvt', """
            import os, sys
            print ( "special env var="+os.environ['SPECIAL_TEST_VAR'] )
            """ )
        os.symlink( util.vvtest, 'vvtest' )
        util.writefile( 'vvtest_bootstrap.py', """
            import os
            os.environ['SPECIAL_TEST_VAR'] = 'special value'
            """ )
        time.sleep(1)

        ok,out = util.run_cmd( os.path.abspath( 'vvtest' ) )
        assert ok
        assert util.numpass( out ) == 1

        fL = glob.glob( 'TestResults*/hello.py*/execute.log' )
        assert len(fL) == 1
        L = util.filegrep( fL[0], 'var=special value' )
        assert len(L) == 1

    def test_a_bootstrap_file_setting_the_config_dir(self):
        ""
        util.writefile( 'myconfig/script_util_plugin.py', """
            import os, sys
            def my_special_func():
                print ( 'my special function called' )
            """ )

        os.symlink( util.vvtest, 'vvtest' )
        util.writefile( 'vvtest_bootstrap.py', """
            import os
            os.environ['VVTEST_CONFIGDIR'] = '"""+os.path.abspath('myconfig')+"""'
            """ )

        util.writefile( 'hello.py.vvt', """
            import os, sys
            import script_util_plugin as util
            util.my_special_func()
            """ )

        time.sleep(1)

        ok,out = util.run_cmd( os.path.abspath( 'vvtest' ) )
        assert ok
        assert util.numpass( out ) == 1

        fL = glob.glob( 'TestResults*/hello.py*/execute.log' )
        assert len(fL) == 1
        L = util.filegrep( fL[0], 'my special function called' )
        assert len(L) == 1

    def test_a_bootstrap_config_dir_is_overridden_with_command_line(self):
        ""
        util.writefile( 'myconfig/script_util_plugin.py', """
            import os, sys
            def my_special_func():
                print ( 'my special function called' )
            """ )

        util.writefile( 'cmdconfig/script_util_plugin.py', """
            import os, sys
            def my_special_func():
                print ( 'command config function called' )
            """ )

        os.symlink( util.vvtest, 'vvtest' )
        util.writefile( 'vvtest_bootstrap.py', """
            import os
            os.environ['VVTEST_CONFIGDIR'] = '"""+os.path.abspath('myconfig')+"""'
            """ )

        util.writefile( 'hello.py.vvt', """
            import os, sys
            import script_util_plugin as util
            util.my_special_func()
            """ )

        time.sleep(1)

        cmd = os.path.abspath( 'vvtest' )
        cmd += ' --config '+os.path.abspath('cmdconfig')
        ok,out = util.run_cmd( cmd )
        assert ok
        assert util.numpass( out ) == 1

        fL = glob.glob( 'TestResults*/hello.py*/execute.log' )
        assert len(fL) == 1
        L = util.filegrep( fL[0], 'my special function called' )
        assert len(L) == 0
        L = util.filegrep( fL[0], 'command config function called' )
        assert len(L) == 1


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
