#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import re
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3

import libvvtest.CommonSpec as CommonSpec
import libvvtest.xmlwrapper as xmlwrapper
import libvvtest.cshScriptWriter as cshScriptWriter
from libvvtest.TestList import createTestObjects
from libvvtest.RuntimeConfig import RuntimeConfig


class FakePlatform:
    def __init__(self): pass
    def getName(self): return "fakeplatform"
    def getCompiler(self): return "fakecompiler"
    def getEnvironment(self):
        D = { 'ENVAR':'envarval' }
        return D


class writing_csh_scripts( vtu.vvtestTestCase ):

    def test_create_runscript_from_xml_specification(self):
        ""
        os.mkdir( 'tdir' )
        testdir = os.path.abspath( 'tdir' )

        util.writefile( 't1.xml', """
            <rtest name="atest">
              <execute name="exename"> echo "hello world" </execute>
            </rtest>
            """ )
        time.sleep(1)

        fn = os.path.join( os.path.dirname( vtu.testsrcdir), 'exeDB.xml' )
        xreader = xmlwrapper.XmlDocReader()
        xdoc = xreader.readDoc( fn )

        xdb = CommonSpec.CommonSpecDB()
        CommonSpec.scanCommonSpecs( xdoc, xdb )

        tL = createTestObjects( '.', 't1.xml', None, RuntimeConfig() )
        assert len(tL) == 1

        plat = FakePlatform()
        toolsdir = os.path.dirname( os.path.dirname( vtu.testsrcdir ) )
        cshScriptWriter.writeScript( tL[0], xdb, plat,
                                     toolsdir, os.getcwd(), testdir,
                                     [], [], 'runscript' )
        time.sleep(1)

        print3( util.readfile( 'runscript' ) )


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
