#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import re

import vvtestutils as vtu
import testutils as util
from testutils import print3

from libvvtest.filtering import file_search
from libvvtest.TestSpecCreator import TestCreator


class filtering_by_file_search( vtu.vvtestTestCase ):

    def test_file_search_function(self):
        ""
        util.writefile( 'regexfile.txt', """
            One line 
            Line Two, then
            line thrEE""" )

        util.writefile( 'ok46.xml', """
            <rtest name="atest">
              <parameterize np="1 4"/>
              <link_files> regexfile.txt </link_files>
            </rtest>""" )

        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('One'), 2 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('three'), 2 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('line two'), 2 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('line one'), 0 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('LINE *THEN'), 0 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('LINE .*THEN'), 2 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('line $'), 2 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('line$'), 0 )
        create_and_search_files( 'ok46.xml', ['*.nun','*.txt'], regexlist('LINE .*THEN'), 2 )
        create_and_search_files( 'ok46.xml', ['*.nun','*.two'], regexlist('LINE .*THEN'), 0 )
        create_and_search_files( 'ok46.xml', ['*.txt'], regexlist('nomatch','LINE .*THEN'), 2 )

        util.writefile( 'ok47.xml', """
            <rtest name="atest">
              <parameterize np="1 4"/>
              <copy_files> regexfile.txt </copy_files>
            </rtest>""" )

        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('One'), 2 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('three'), 2 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('line two'), 2 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('line one'), 0 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('LINE *THEN'), 0 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('LINE .*THEN'), 2 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('line $'), 2 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('line$'), 0 )
        create_and_search_files( 'ok47.xml', ['*.nun','*.txt'], regexlist('LINE .*THEN'), 2 )
        create_and_search_files( 'ok47.xml', ['*.nun','*.two'], regexlist('LINE .*THEN'), 0 )
        create_and_search_files( 'ok47.xml', ['*.txt'], regexlist('nomatch','LINE .*THEN'), 2 )

        util.writefile( 'ok48.xml', """
            <rtest name="atest">
              <parameterize np="1 4"/>
              <copy_files> noexist.txt </copy_files>
            </rtest>""" )

        create_and_search_files( 'ok48.xml', ['*.txt'], regexlist('One'), 0 )

        util.writefile( 'ok49.xml', """
            <rtest name="regexfile">
              <parameterize np="1 4"/>
              <copy_files> $NAME.txt </copy_files>
            </rtest>""" )

        create_and_search_files( 'ok49.xml', ['*.txt'], regexlist('One'), 2 )

        util.writefile( 'ok50.xml', """
            <rtest name="regex">
              <parameterize np="1 4"/>
              <copy_files> ${NAME}file.txt </copy_files>
            </rtest>""" )

        create_and_search_files( 'ok50.xml', ['*.txt'], regexlist('One'), 2 )

    def test_filter_tests_by_input_file_search(self):
        ""
        util.writefile( 'solar.inp', """
            foo and bar
            this and that
            """ )
        util.writefile( 'solar.xml', """
            <rtest name="solar">
              <execute> echo "solar ran" </execute>
              <link_files> solar.inp </link_files>
            </rtest>""" )
        util.writescript( 'extrasolar.vvt', """
            #!"""+sys.executable+"""
            #VVT: link : solar.inp
            import os
            print ( "extrasolar ran" )
            """ )
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            vtu.remove_results()
            vrun = vtu.runvvtest( '--search foo', batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            vtu.remove_results()
            vrun = vtu.runvvtest( '--search aliensrock', batch=batch )
            vrun.assertCounts( total=0 )

            vtu.remove_results()
            vrun = vtu.runvvtest( '--search foo', batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            vrun = vtu.runvvtest( '-R --search aliensrock', batch=batch )
            vrun.assertCounts( total=0 )

            vrun = vtu.runvvtest( '-R --search foo', batch=batch )
            vrun.assertCounts( total=2, npass=2 )


def regexlist( *patterns ):
    ""
    rxL = []
    for pat in patterns:
        rxL.append( re.compile( pat, re.IGNORECASE | re.MULTILINE ) )
    return rxL


def create_tests( relpath, platname='dummy', optlist=[] ):
    ""
    creator = TestCreator( platname, optlist )
    tL = creator.fromFile( os.getcwd(), relpath, None )
    sortL = [ (ts.getDisplayString(),ts) for ts in tL ]
    sortL.sort()
    tL = [ T[1] for T in sortL ]
    return tL


def create_and_search_files( filename, globlist, regexes, test_count ):
    ""
    tL = create_tests( filename )

    cnt = 0

    for tspec in tL:
        if file_search( tspec, regexes, globlist ):
            cnt += 1

    assert cnt == test_count


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
