#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import glob

import vvtestutils as vtu
import testutils as util
from testutils import print3


class options_tests( vtu.vvtestTestCase ):

    def test_spot_check_each_mode_of_operation(self):
        ""
        util.writefile( "null.xml", """
            <rtest name="null">
            </rtest>""" )
        time.sleep(1)

        vtu.runvvtest( '-h' )
        vtu.runvvtest( '--help' )

        vtu.runvvtest( '-g' )
        vrun = vtu.runvvtest()
        vrun.assertCounts( total=1, npass=1 )
        assert len( glob.glob( 'TestResults*' ) ) == 1

        vtu.runvvtest( '-i' ).assertCounts( total=1, npass=1 )

        vtu.runvvtest( '-b' )

    def test_some_bad_option_values(self):
        ""
        self.assertRaises( Exception, vtu.runvvtest, '-n text' )
        self.assertRaises( Exception, vtu.runvvtest, '-n -3' )


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
