#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import glob
import unittest

import vvtestutils as vtu
import testutils as util
from testutils import print3


class options_tests( unittest.TestCase ):

    def setUp(self):
        util.setup_test()

    def test_of_each_mode_of_operation(self):
        ""
        util.writefile( "null.xml", """
            <rtest name="null">
            </rtest>""" )
        time.sleep(1)

        vtu.runvvtest( '-h' )
        vtu.runvvtest( '-H' )
        vtu.runvvtest( '--help' )

        vtu.runvvtest( '-g' )
        vrun = vtu.runvvtest()
        vrun.assertCounts( total=1, npass=1 )
        assert len( glob.glob( 'TestResults*' ) ) == 1

        vtu.runvvtest( '-i' ).assertCounts( total=1, npass=1 )

        vtu.runvvtest( '-b' )

    def test_mode_combinations_that_are_not_allowed(self):
        ""
        self.assertRaises( Exception, vtu.runvvtest, '-gi' )
        self.assertRaises( Exception, vtu.runvvtest, '-gb' )
        self.assertRaises( Exception, vtu.runvvtest, '-Ri' )
        self.assertRaises( Exception, vtu.runvvtest, '-Rb' )
        self.assertRaises( Exception, vtu.runvvtest, '-ib' )

    def test_some_bad_option_values(self):
        ""
        self.assertRaises( Exception, vtu.runvvtest, '-j dir1 -j dir2' )
        self.assertRaises( Exception, vtu.runvvtest, '-M dir1 -M dir2' )
        self.assertRaises( Exception, vtu.runvvtest, '-n 1 -n 2' )
        self.assertRaises( Exception, vtu.runvvtest, '-n text' )
        self.assertRaises( Exception, vtu.runvvtest, '-n -3' )


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
