#!/usr/bin/env python
#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import re
import time
import filecmp
import shutil
import glob
import stat

import testutils as util
optD,argL = util.initialize( sys.argv )
if 'TESTUTILS_RUNDIR' not in os.environ:
    os.chdir( util.working_directory )

from testutils import *


def main():
    """
    """
    global argL

    if len(argL) == 0:
        argL = """test01 test02
               """.split()

    savedir = os.getcwd()
    for func in argL:
        os.chdir( savedir )
        rmallfiles()
        time.sleep(1)
        print3( '====> ', func )

        # for batch tests
        os.environ['VVTEST_BATCH_READ_INTERVAL'] = '5'
        os.environ['VVTEST_BATCH_READ_TIMEOUT'] = '15'
        os.environ['VVTEST_BATCH_SLEEP_LENGTH'] = '1'

        eval( func+'()' )


########################################################################

def test01():
    """
    turn off all group and world permissions
    """
    writefile( "one/cat.xml", """
        <rtest name="cat">
          <execute>
            sleep 1
          </execute>
        </rtest>""" )
    writefile( "one/dog.xml", """
        <rtest name="dog">
          <execute>
            sleep 2
          </execute>
        </rtest>""" )
    writefile( "two/circle.xml", """
        <rtest name="circle">
          <execute>
            sleep 3
          </execute>
        </rtest>""" )

    run_test01( '' )
    run_test01( '--plat '+core_platform_name()+' --batch' )

def run_test01( opt ):
    ""
    remove_results()

    out,np,nd,nf,nn = run_vvtest( opt+' --perms g=,o=' )
    assert np == 3 and nd == 0 and nf == 0 and nn == 0
    tdir = os.path.abspath( results_dir() )
    platname = platform_name( out )

    m = stat.S_IMODE( os.stat(tdir)[stat.ST_MODE] )
    assert int( m & stat.S_IRWXG ) == 0
    assert int( m & stat.S_IRWXO ) == 0

    for f in 'test.cache testlist one two'.split():
        p = os.path.join( tdir, f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & stat.S_IRWXG ) == 0
        assert int( m & stat.S_IRWXO ) == 0

    for f in 'cat dog'.split():
        p = os.path.join( tdir, 'one', f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & stat.S_IRWXG ) == 0
        assert int( m & stat.S_IRWXO ) == 0

    for f in 'execute.log runscript'.split():
        p = os.path.join( tdir, 'one', 'dog', f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & stat.S_IRWXG ) == 0
        assert int( m & stat.S_IRWXO ) == 0


def test02():
    """
    turn on group and world permissions
    """
    writefile( "one/cat.xml", """
        <rtest name="cat">
          <execute>
            sleep 1
          </execute>
        </rtest>""" )
    writefile( "one/dog.xml", """
        <rtest name="dog">
          <execute>
            sleep 2
          </execute>
        </rtest>""" )
    writefile( "two/circle.xml", """
        <rtest name="circle">
          <execute>
            sleep 3
          </execute>
        </rtest>""" )

    run_test02( '' )
    run_test02( '--plat '+core_platform_name()+' --batch' )

def run_test02( opt ):
    ""
    remove_results()

    out,np,nd,nf,nn = run_vvtest( opt+' --perms g=rws,o=rwx' )
    assert np == 3 and nd == 0 and nf == 0 and nn == 0
    tdir = os.path.abspath( results_dir() )
    platname = platform_name( out )

    m = stat.S_IMODE( os.stat(tdir)[stat.ST_MODE] )
    assert int( m & (stat.S_IRWXG|stat.S_ISGID) ) == int( stat.S_IRWXG|stat.S_ISGID )
    assert int( m & stat.S_IRWXO ) == stat.S_IRWXO

    for f in 'test.cache testlist'.split():
        p = os.path.join( tdir, f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & stat.S_IRWXG ) == int( stat.S_IRGRP|stat.S_IWGRP )
        assert int( m & stat.S_IRWXO ) == int( stat.S_IROTH|stat.S_IWOTH )

    fL = ['one','two']
    if 'batch' in opt:
        fL.append( 'batchset0' )
    for f in fL:
        p = os.path.join( tdir, f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & (stat.S_IRWXG|stat.S_ISGID) ) == int( stat.S_IRWXG|stat.S_ISGID )
        assert int( m & stat.S_IRWXO ) == stat.S_IRWXO

    if 'batch' in opt:
        for f in os.listdir( os.path.join( tdir, 'batchset0' ) ):
            p = os.path.join( tdir, 'batchset0', f )
            m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
            assert int( m & stat.S_IRWXG ) == int( stat.S_IRGRP|stat.S_IWGRP )
            assert int( m & stat.S_IRWXO ) == int( stat.S_IROTH|stat.S_IWOTH )

    for f in 'cat dog'.split():
        p = os.path.join( tdir, 'one', f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & (stat.S_IRWXG|stat.S_ISGID) ) == int( stat.S_IRWXG|stat.S_ISGID )
        assert int( m & stat.S_IRWXO ) == stat.S_IRWXO

    for f in 'execute.log'.split():
        p = os.path.join( tdir, 'one', 'dog', f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & stat.S_IRWXG ) == int( stat.S_IRGRP|stat.S_IWGRP )
        assert int( m & stat.S_IRWXO ) == int( stat.S_IROTH|stat.S_IWOTH )

    for f in 'runscript'.split():
        p = os.path.join( tdir, 'one', 'dog', f )
        m = stat.S_IMODE( os.stat(p)[stat.ST_MODE] )
        assert int( m & stat.S_IRWXG ) == int( stat.S_IRGRP|stat.S_IWGRP|stat.S_IXGRP )
        assert int( m & stat.S_IRWXO ) == int( stat.S_IROTH|stat.S_IWOTH|stat.S_IXOTH )


############################################################################

main()
