#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3


class tests_that_run_vvtest( vtu.vvtestTestCase ):

    def test_a_test_that_runs_vvtest(self):
        ""
        plat = vtu.core_platform_name()

        util.writefile( 'outside.py.vvt', """
            import os
            import vvtest_util as vvt
            import script_util as util

            fp = open( 'inside.py.vvt', 'w' )
            fp.write( "import vvtest_util as vvt"+os.linesep )
            fp.write( "fp = open( 'hello.txt', 'w' )"+os.linesep )
            fp.write( "fp.write( 'world'+os.linesep )"+os.linesep )
            fp.write( "fp.close()"+os.linesep )
            fp.close()

            util.runcmd( '"""+vtu.vvtest_file+""" -k inside.py --plat """+plat+"""' )
            """ )
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( batch=batch )
            vrun.assertCounts( total=1, npass=1 )

            assert len( util.findfiles( 'hello.txt', vrun.resultsDir() ) ) == 1


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
