#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3


class runtimes_and_tmin_tmax( vtu.vvtestTestCase ):

    def test_tmin_tmax_using_previous_test_results_timings(self):
        ""
        util.writescript( "AA.vvt", """
            #!"""+sys.executable+"""
            import os, sys, time
            time.sleep(1)
            """ )
        util.writescript( "BB.vvt", """
            #!"""+sys.executable+"""
            import os, sys, time
            time.sleep(3)
            """ )
        util.writescript( "CC.vvt", """
            #!"""+sys.executable+"""
            import os, sys, time
            time.sleep(7)
            """ )
        time.sleep(1)

        vtu.runvvtest().assertCounts( total=3, npass=3 )

        vtu.runvvtest( '-i' ).assertCounts( total=3, npass=3 )

        vrun = vtu.runvvtest( '-i --tmax 6' )
        vrun.assertCounts( total=2, npass=2 )
        assert vrun.getTestIds() == [ 'AA', 'BB' ]

        vrun = vtu.runvvtest( '-i --tmin 3' )
        vrun.assertCounts( total=2, npass=2 )
        assert vrun.getTestIds() == [ 'BB', 'CC' ]

    def test_using_tmin_tmax_wont_destroy_previous_results(self):
        """
        runtime min/max with excluding previously run tests
        """
        util.writescript( "tests/AA.vvt", """
            #!"""+sys.executable+"""
            import os, sys, time
            time.sleep(1)
            """ )
        util.writescript( "tests/BB.vvt", """
            #!"""+sys.executable+"""
            #VVT: parameterize : planet=mercury mars venus
            #VVT: analyze : --analyze
            import os, sys, time
            import vvtest_util as vvt
            if '--analyze' not in sys.argv:
                if vvt.planet == 'mercury':
                    time.sleep(1)
                elif vvt.planet == 'mars':
                    time.sleep(3)
                elif vvt.planet == 'venus':
                    time.sleep(7)
            else:
                pass  # the analyze test
            """ )
        util.writescript( "tests/CC.vvt", """
            #!"""+sys.executable+"""
            import os, sys, time
            time.sleep(7)
            """ )
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( 'tests', batch=batch )
            vrun.assertCounts( total=6, npass=6 )
            tdir = vrun.resultsDir()

            vrun = vtu.runvvtest( '--tmin 3 tests', batch=batch )
            vrun.assertCounts( total=0 )

            # check that the test list in TestResults.* directory is intact
            vrun = vtu.runvvtest( '-i', chdir=tdir )
            vrun.assertCounts( total=6, npass=6 )

            vrun = vtu.runvvtest( '-R --tmin 3 tests', batch=batch )
            vrun.assertCounts( total=3, npass=3 )
            assert vrun.getTestIds() == \
                        [ 'BB.planet=mars', 'BB.planet=venus', 'CC' ]

            # check that the test list in TestResults.* directory has old results
            vrun = vtu.runvvtest( '-i', chdir=tdir )
            vrun.assertCounts( total=6, npass=6 )


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
