#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3


class runtimes_and_tsum( vtu.vvtestTestCase ):

    def test_filter_tests_by_sum_of_runtimes(self):
        ""
        util.writescript( "tests/AA.vvt", """
            #!"""+sys.executable+"""
            import os, sys, time
            time.sleep(1)
            """ )
        util.writescript( "tests/BB.vvt", """
            #!"""+sys.executable+"""
            #VVT: parameterize : planet=mercury mars venus
            #VVT: analyze : --analyze
            import os, sys, time
            import vvtest_util as vvt
            if '--analyze' not in sys.argv:
                if vvt.planet == 'mercury':
                    time.sleep(3)
                elif vvt.planet == 'mars':
                    time.sleep(4)
                elif vvt.planet == 'venus':
                    time.sleep(5)
            else:
                time.sleep(3)  # the analyze test
            """ )
        util.writescript( "tests/CC.vvt", """
            #!"""+sys.executable+"""
            import os, sys, time
            time.sleep(2)
            """ )
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( '--tsum 7 tests', batch=batch )
            vrun.assertCounts( total=6, npass=6 )

            vrun = vtu.runvvtest( '-R --tsum 7 tests', batch=batch )
            vrun.assertCounts( total=2, npass=2 )
            assert vrun.getTestIds() == [ 'AA', 'CC' ]

            # check that the full list is still intact
            vrun = vtu.runvvtest( '-R tests', batch=batch )
            vrun.assertCounts( total=6, npass=6 )


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
