#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import glob
import unittest

import testutils as util
from testutils import print3


class script_tests( unittest.TestCase ):

    def setUp(self):
        util.setup_test()

    def test_an_executable_script_as_a_test_file(self):
        ""
        util.writescript( 'hello.vvt', """
            #!/bin/sh
            echo "hello from the hello test script"
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=1, npass=1 )
        assert vrun.getTestIds() == [ 'hello' ]
        assert vrun.countGrepLogs( 'hello from the hello test script' ) == 1

    def test_that_the_test_name_can_be_different_than_the_script_name(self):
        ""
        util.writescript( 'hello.vvt', """
            #!/bin/sh
            #VVT: name=world
            echo "hello from the hello/world test script"
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=1, npass=1 )
        assert vrun.getTestIds() == [ 'world' ]
        assert vrun.countGrepLogs( 'hello from the hello/world test script' ) == 1

    def test_that_python_is_always_used_to_run_non_executable_scripts(self):
        ""
        util.writefile( 'hello.vvt',
            "#!/bin/sh\n" + \
            "print ( 'hello from the hello test script' )\n" )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=1, npass=1 )
        assert vrun.getTestIds() == [ 'hello' ]
        assert vrun.countGrepLogs( 'hello from the hello test script' ) == 1

    def test_importing_the_helper_fragment(self):
        ""
        util.writefile( 'hello.py.vvt', """
            import os, sys
            print ( "hello from the python test script" )
            import vvtest_util as vvt
            print ( 'hello, dir=', dir(vvt) )

            assert hasattr( vvt, 'NAME' )
            assert hasattr( vvt, 'TESTID' )
            assert hasattr( vvt, 'PLATFORM' )
            assert hasattr( vvt, 'COMPILER' )
            assert hasattr( vvt, 'VVTESTSRC' )
            assert hasattr( vvt, 'CONFIGDIR' )
            assert hasattr( vvt, 'PROJECT' )
            assert hasattr( vvt, 'OPTIONS' )
            assert hasattr( vvt, 'OPTIONS_OFF' )
            assert hasattr( vvt, 'SRCDIR' )

            assert vvt.NAME == 'hello.py'
            print ( 'PROJECT = '+vvt.PROJECT )
            assert vvt.OPTIONS == ['dbg']
            """ )
        os.mkdir( 'bin' )
        time.sleep(1)

        for batch in [False,True]:

            util.remove_results()

            vrun = util.runvvtest( '-j bin -o dbg', batch=batch )
            vrun.assertCounts( total=1, npass=1 )
            assert vrun.getTestIds() == [ 'hello.py' ]

            assert vrun.countGrepLogs( 'hello from the python test script' ) == 1

            L = vrun.greplogs( 'PROJECT =' )
            assert len(L) == 1
            assert L[0].split('=',1)[1].strip() == os.path.abspath('bin')

    def test_a_python_test_that_exits_with_a_diff_a_pass_and_a_fail(self):
        ""
        util.writescript( 'tpass.vvt', """
            #!/usr/bin/env python
            import os, sys
            import vvtest_util as vvt
            """ )
        util.writescript( 'tdiff.vvt', """
            #!/usr/bin/env python
            import os, sys
            from script_util import *
            exit_diff()
            """ )
        util.writescript( 'tfail.vvt', """
            #!/usr/bin/env python
            import os, sys
            def myfunc():
                raise Exception( "test failed" )
            myfunc()
            """ )
        time.sleep(1)

        for batch in [False,True]:

            util.remove_results()

            vrun = util.runvvtest( batch=batch )
            vrun.assertCounts( total=3, npass=1, diff=1, fail=1 )

    def test_multiple_tests_in_one_script_file(self):
        ""
        util.writescript( 'multi.vvt', """
            #!/usr/bin/env python
            #VVT: name=multi
            #VVT: name=multi2
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        time.sleep(1)

        for batch in [False,True]:

            util.remove_results()

            vrun = util.runvvtest( batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            assert vrun.getTestIds() == [ 'multi', 'multi2' ]

            assert vrun.countGrepLogs( 'hello from the multi test' ) == 1
            assert vrun.countGrepLogs( 'hello from the multi2 test' ) == 1

    def test_header_specification_comment_variations(self):
        ""
        util.writescript( 'tst1.vvt', """
            #!/usr/bin/env python

            #VVT: name=test1
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst2.vvt', """
            #!/usr/bin/env python
            # 
            #VVT: name=test2
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst3.vvt', """
            #!/usr/bin/env python
            import vvtest_util as vvt
            #VVT: name=test3
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst4.vvt', """
            #!/usr/bin/env python
            #VVT: name=test4a

            #VVT: name=test4b

            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst5.vvt', """
            #!/usr/bin/env python
            # regular comments can be interleaved
            #VVT: name=test5a

            # this test should also be run
            #VVT: name=test5b

            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=7, npass=7 )

        assert vrun.getTestIds() == [ 'test1',
                                      'test2',
                                      'test4a',
                                      'test4b',
                                      'test5a',
                                      'test5b',
                                      'tst3' ]

        assert vrun.countGrepLogs( 'hello from the test1 test' ) == 1
        assert vrun.countGrepLogs( 'hello from the test2 test' ) == 1
        assert vrun.countGrepLogs( 'hello from the tst3 test' ) == 1
        assert vrun.countGrepLogs( 'hello from the test4a test' ) == 1
        assert vrun.countGrepLogs( 'hello from the test4b test' ) == 1
        assert vrun.countGrepLogs( 'hello from the test5a test' ) == 1
        assert vrun.countGrepLogs( 'hello from the test5b test' ) == 1

    def test_incorrect_specification_syntax(self):
        ""
        util.writescript( 'tst1.vvt', """
            #!/usr/bin/env python
            #VVT: =junk
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst2.vvt', """
            #!/usr/bin/env python
            #VVT: keywords (testname=tst2) foo : bar
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst2b.vvt', """
            #!/usr/bin/env python
            #VVT: keywords (testname=tst2b) foo
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst2c.vvt', """
            #!/usr/bin/env python
            #VVT: keywords (testname=tst2c) (testname=tst2b)
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst3.vvt', """
            #!/usr/bin/env python
            #VVT: keywords (testname=tst3) : junk
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst4.vvt', """
            #!/usr/bin/env python
            #VVT::
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst5.vvt', """
            #!/usr/bin/env python
            #VVT: keywords (=tst5) : foo bar
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst6.vvt', """
            #!/usr/bin/env python
            #VVT: keywords (foo=bar,=) : foo bar
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        util.writescript( 'tst7.vvt', """
            #!/usr/bin/env python
            #VVT: keywords (foo=bar : foo bar
            import vvtest_util as vvt
            print ( "hello from the "+vvt.NAME+" test" )
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=1, npass=1 )

        assert len( vrun.grep( 'skipping .*tst1.vvt'  ) ) == 1
        assert len( vrun.grep( 'skipping .*tst2.vvt'  ) ) == 1
        assert len( vrun.grep( 'skipping .*tst2b.vvt'  ) ) == 1
        assert len( vrun.grep( 'skipping .*tst2c.vvt'  ) ) == 1
        assert len( vrun.grep( 'skipping .*tst4.vvt'  ) ) == 1
        assert len( vrun.grep( 'skipping .*tst5.vvt'  ) ) == 1
        assert len( vrun.grep( 'skipping .*tst6.vvt'  ) ) == 1
        assert len( vrun.grep( 'skipping .*tst7.vvt'  ) ) == 1

        assert vrun.countGrepLogs( 'hello from the tst3 test' ) == 1

    def test_using_the_have_diff_utility(self):
        ""
        util.writescript( 'pypass.vvt', """
            #!/usr/bin/env python
            import os, sys
            from script_util import *
            if_diff_exit_diff()
            """ )
        util.writescript( 'pydiff.vvt', """
            #!/usr/bin/env python
            import os, sys
            from script_util import *
            set_have_diff()
            if_diff_exit_diff()
            """ )
        util.writescript( 'pydiff2.vvt', """
            #!/usr/bin/env python
            import os, sys
            from script_util import *
            exit_diff()
            """ )
        util.writescript( 'shpass.vvt', """
            #!/bin/sh
            source ./vvtest_util.sh
            if_diff_exit_diff
            """ )
        util.writescript( 'shdiff.vvt', """
            #!/bin/sh
            source ./vvtest_util.sh
            set_have_diff
            if_diff_exit_diff
            """ )
        util.writescript( 'shdiff2.vvt', """
            #!/bin/sh
            source ./vvtest_util.sh
            exit_diff
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=6, npass=2, diff=4 )

        assert vrun.countGrepLogs( 'exiting diff', 'pydiff$' ) == 1
        assert vrun.countGrepLogs( 'exiting diff', 'shdiff$' ) == 1
        assert vrun.countGrepLogs( 'exiting diff', 'pypass' ) == 0
        assert vrun.countGrepLogs( 'exiting diff', 'shpass' ) == 0

        util.remove_results()

        vrun = util.runvvtest( batch=True )
        vrun.assertCounts( total=6, npass=2, diff=4 )

        assert vrun.countGrepLogs( 'exiting diff', 'pydiff$' ) == 1
        assert vrun.countGrepLogs( 'exiting diff', 'shdiff$' ) == 1
        assert vrun.countGrepLogs( 'exiting diff', 'pypass' ) == 0
        assert vrun.countGrepLogs( 'exiting diff', 'shpass' ) == 0

        vrun = util.runvvtest( '-R', chdir=vrun.resultsDir() )
        vrun.assertCounts( total=6, npass=2, diff=4 )

        assert vrun.countGrepLogs( 'exiting diff', 'pydiff$' ) == 1
        assert vrun.countGrepLogs( 'exiting diff', 'shdiff$' ) == 1
        assert vrun.countGrepLogs( 'exiting diff', 'pypass' ) == 0
        assert vrun.countGrepLogs( 'exiting diff', 'shpass' ) == 0

    def test_the_sedfile_utility(self):
        ""
        util.writefile( 'changeme.txt', """
            the quick brown fox jumps
            over the lazy dog
            """ )
        util.writescript( 'pytest.vvt', """
            #!/usr/bin/env python
            #VVT: link = changeme.txt
            import os
            from script_util import *
            assert os.path.islink( 'changeme.txt' )
            sedfile( 'changeme.txt', 'quick', 'lazy', 'jumps', 'steps' )
            assert not os.path.islink( 'changeme.txt' )
            """ )
        util.writescript( 'shtest.vvt', """
            #!/bin/sh
            #VVT: link = changeme.txt
            source ./vvtest_util.sh
            sedfile changeme.txt "s/quick/speedy/"
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=2, npass=2 )

        assert util.readfile( 'changeme.txt' ).strip() == \
            "the quick brown fox jumps\nover the lazy dog"

        tdir = vrun.resultsDir()

        assert not os.path.islink( tdir+'/pytest/changeme.txt' )
        assert util.readfile( tdir+'/pytest/changeme.txt' ).strip() == \
            "the lazy brown fox steps\nover the lazy dog"

        assert not os.path.islink( tdir+'/shtest/changeme.txt' )
        assert util.readfile( tdir+'/shtest/changeme.txt' ).strip() == \
            "the speedy brown fox jumps\nover the lazy dog"

    def test_the_unixdiff_utility(self):
        ""
        util.writefile( 'baseline.txt',
                   'the quick brown fox jumps\n' + \
                   'over the lazy dog' )
        util.writescript( 'pypass.vvt', """
            #!/usr/bin/env python
            #VVT: link = baseline.txt
            import os
            from script_util import *
            fp = open( 'genfile.txt', 'w' )
            fp.write( 'the quick brown fox jumps\\n' + \
                      'over the lazy dog\\n' )
            fp.close()
            unixdiff( 'baseline.txt', 'genfile.txt' )
            if_diff_exit_diff()
            """ )
        util.writescript( 'pydiff.vvt', """
            #!/usr/bin/env python
            #VVT: link = baseline.txt
            import os
            from script_util import *
            fp = open( 'genfile.txt', 'w' )
            fp.write( 'the quick brown fox jumps\\n' + \
                      'over the super lazy dog\\n' )
            fp.close()
            unixdiff( 'baseline.txt', 'genfile.txt' )
            if_diff_exit_diff()
            """ )
        util.writescript( 'shpass.vvt', """
            #!/bin/sh
            #VVT: link = baseline.txt
            source ./vvtest_util.sh
            echo "the quick brown fox jumps" > genfile.txt
            echo "over the lazy dog" >> genfile.txt
            echo "" >> genfile.xt
            unixdiff baseline.txt genfile.txt
            if_diff_exit_diff
            """ )
        util.writescript( 'shdiff.vvt', """
            #!/bin/sh
            #VVT: link = baseline.txt
            source ./vvtest_util.sh
            echo "the quick brown fox jumps" > genfile.txt
            echo "over the utterly lazy dog" >> genfile.txt
            echo "" >> genfile.xt
            unixdiff baseline.txt genfile.txt
            if_diff_exit_diff
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=4, npass=2, diff=2 )

        assert vrun.countGrepLogs( 'files are diff', 'pypass' ) == 0
        assert vrun.countGrepLogs( 'files are diff', 'pydiff' ) == 1
        assert vrun.countGrepLogs( 'files are diff', 'shpass' ) == 0
        assert vrun.countGrepLogs( 'files are diff', 'shdiff' ) == 1

    def test_the_nlinesdiff_utility(self):
        ""
        util.writescript( 'pypass.vvt', """
            #!/usr/bin/env python
            import os
            from script_util import *
            fp = open( 'genfile.txt', 'w' )
            fp.write( 'the speedy brown fox jumps\\n' + \
                      'over the lazy dog\\n' )
            fp.close()
            nlinesdiff( 'genfile.txt', 2 )
            if_diff_exit_diff()
            """ )
        util.writescript( 'pydiff.vvt', """
            #!/usr/bin/env python
            import os
            from script_util import *
            fp = open( 'genfile.txt', 'w' )
            fp.write( 'the speedy brown fox jumps\\n' + \
                      'over the super lazy dog\\n' + \
                      'and laughed\\n' )
            fp.close()
            nlinesdiff( 'genfile.txt', 2 )
            if_diff_exit_diff()
            """ )
        util.writescript( 'shpass.vvt', """
            #!/bin/sh
            source ./vvtest_util.sh
            echo "the speedy brown fox jumps" > genfile.txt
            echo "over the lazy dog" >> genfile.txt
            nlinesdiff genfile.txt 2
            if_diff_exit_diff
            """ )
        util.writescript( 'shdiff.vvt', """
            #!/bin/sh
            source ./vvtest_util.sh
            echo "the speedy brown fox jumps" > genfile.txt
            echo "over the lazy dog" >> genfile.txt
            echo "and laughed" >> genfile.txt
            nlinesdiff genfile.txt 2
            if_diff_exit_diff
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=4, npass=2, diff=2 )

        assert vrun.countGrepLogs( 'number of lines exceeded', 'pypass' ) == 0
        assert vrun.countGrepLogs( 'number of lines exceeded', 'pydiff' ) == 1
        assert vrun.countGrepLogs( 'number of lines exceeded', 'shpass' ) == 0
        assert vrun.countGrepLogs( 'number of lines exceeded', 'shdiff' ) == 1

    def test_copy_and_link_files_specification(self):
        ""
        util.writefile( 'file1.txt', """
            this is file one
            """ )
        util.writefile( 'file2.txt', """
            this is file two
            """ )
        util.writefile( 'file3.txt', """
            this is file three
            """ )
        util.writescript( 'files.vvt', """
            #!/usr/bin/env python
            #VVT: link : file1.txt file2.txt
            #VVT: copy : file3.txt
            #VVT: link (rename) : file1.txt, lfile1 file2.txt,lfile2
            #VVT: copy (rename) : file3.txt ,cfile3
            import os
            assert os.path.exists( 'file1.txt' )
            assert os.path.islink( 'file1.txt' )
            assert os.path.exists( 'file2.txt' )
            assert os.path.islink( 'file2.txt' )
            assert os.path.exists( 'file3.txt' )
            assert not os.path.islink( 'file3.txt' )
            assert os.path.exists( 'lfile1' )
            assert os.path.islink( 'lfile1' )
            assert os.path.exists( 'lfile2' )
            assert os.path.islink( 'lfile2' )
            assert os.path.exists( 'cfile3' )
            assert not os.path.islink( 'cfile3' )

            import filecmp
            assert filecmp.cmp( 'file1.txt', 'lfile1', shallow=False )
            assert filecmp.cmp( 'file2.txt', 'lfile2', shallow=False )
            assert filecmp.cmp( 'file3.txt', 'cfile3', shallow=False )
            """ )
        time.sleep(1)

        for batch in [False,True]:

            util.remove_results()

            vrun = util.runvvtest( batch=batch )
            vrun.assertCounts( total=1, npass=1 )

    def test_copy_and_link_files_with_attribute_specifications(self):
        ""
        platname = util.core_platform_name()

        util.writefile( 'file1.txt', """
            this is file one
            """ )
        util.writefile( 'file2.txt', """
            this is file two
            """ )
        util.writefile( 'file3.txt', """
            this is file three
            """ )
        util.writefile( 'file4.txt', """
            this is file four
            """ )
        util.writefile( 'file5.txt', """
            this is file five
            """ )
        util.writescript( 'files.vvt', """
            #!/usr/bin/env python
            
            #VVT: name = files
            #VVT: name = another
            #VVT: link (testname=files): file1.txt
            #VVT: link (testname=not files): file2.txt
            #VVT: copy (options=dbg, testname=another) : file3.txt
            #VVT: link (rename, platforms="Junk") : file4.txt, lfile4
            #VVT: copy (rename, platforms="""+platname+""") : file5.txt,cfile5
            
            import os
            import script_util as vvt
            if vvt.NAME == 'files':
                assert os.path.exists( 'file1.txt' )
                assert os.path.islink( 'file1.txt' )
                assert not os.path.exists( 'file2.txt' )
            else:
                assert os.path.exists( 'file2.txt' )
                assert os.path.islink( 'file2.txt' )
            if 'dbg' in vvt.OPTIONS and vvt.NAME == 'another':
                assert os.path.exists( 'file3.txt' )
                assert not os.path.islink( 'file3.txt' )
            else:
                assert not os.path.exists( 'file3.txt' )
            assert not os.path.exists( 'file4.txt' )
            assert not os.path.exists( 'lfile4' )
            assert os.path.exists( 'cfile5' )
            assert not os.path.islink( 'cfile5' )
            """ )
        time.sleep(1)

        for batch in [False,True]:

            util.remove_results()

            vrun = util.runvvtest( batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            util.remove_results()

            vrun = util.runvvtest( '-o dbg', batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            fL = glob.glob( 'TestResults*/another/file3.txt' )
            assert len(fL) == 1
            assert not os.path.islink( fL[0] )

    def test_using_the_vvtest_system_utility_functions(self):
        ""
        platname = util.core_platform_name()

        util.writescript( 'pytest.vvt', """
            #!/usr/bin/env python
            #VVT: parameterize : A = 1 3 5
            import script_util as vvt
            print3 = vvt.print3
            if vvt.parameter_expr( "A<3 or A=5" ):
                print3( "with A="+vvt.A+" param expr true" )
            else:
                print3( "with A="+vvt.A+" param expr false" )
            if vvt.platform_expr( 'Junk or """+platname+"""' ):
                print3( "plat expr true" )
            else:
                print3( "plat expr false" )
            if vvt.platform_expr( 'Junk' ):
                print3( "plat expr2 true" )
            else:
                print3( "plat expr2 false" )
            if vvt.option_expr( 'dbg and not intel' ):
                print3( "option expr true" )
            else:
                print3( "option expr false" )
            """ )
        util.writescript( 'shtest.vvt', """
            #!/bin/sh
            #VVT: parameterize : B = 1 3 5
            source ./vvtest_util.sh
            if parameter_expr "B<3 or B=5"
            then
                echo "with B=$B param expr true"
            else
                echo "with B=$B param expr false"
            fi
            if platform_expr 'Junk or """+platname+"""'
            then
                echo "plat expr true"
            else
                echo "plat expr false"
            fi
            if platform_expr 'Junk'
            then
                echo "plat expr2 true"
            else
                echo "plat expr2 false"
            fi
            if option_expr 'dbg and not intel'
            then
                echo "option expr true"
            else
                echo "option expr false"
            fi
            """ )
        time.sleep(1)

        for batch in [False,True]:

            util.remove_results()

            vrun = util.runvvtest( batch=batch )
            vrun.assertCounts( total=6, npass=6 )

            assert vrun.countGrepLogs( 'with A=1 param expr true',
                                       'pytest.A=1' ) == 1
            assert vrun.countGrepLogs( 'with A=3 param expr false',
                                       'pytest.A=3' ) == 1
            assert vrun.countGrepLogs( 'with A=5 param expr true',
                                       'pytest.A=5' ) == 1
            assert vrun.countGrepLogs( 'with B=1 param expr true',
                                       'shtest.B=1' ) == 1
            assert vrun.countGrepLogs( 'with B=3 param expr false',
                                       'shtest.B=3' ) == 1
            assert vrun.countGrepLogs( 'with B=5 param expr true',
                                       'shtest.B=5' ) == 1

            assert vrun.countGrepLogs( 'plat expr true', 'pytest.A=3' ) == 1
            assert vrun.countGrepLogs( 'plat expr2 false', 'pytest.A=3' ) == 1
            assert vrun.countGrepLogs( 'plat expr true', 'shtest.B=5' ) == 1
            assert vrun.countGrepLogs( 'plat expr2 false', 'shtest.B=5' ) == 1

            assert vrun.countGrepLogs( 'option expr false', 'pytest.A=1' ) == 1
            assert vrun.countGrepLogs( 'option expr false', 'shtest.B=1' ) == 1

            util.remove_results()

            vrun = util.runvvtest( '-o dbg', batch=batch )
            vrun.assertCounts( total=6, npass=6 )

            assert vrun.countGrepLogs( 'option expr true', 'pytest.A=1' ) == 1
            assert vrun.countGrepLogs( 'option expr true', 'shtest.B=1' ) == 1

            util.remove_results()

            vrun = util.runvvtest( '-o dbg+intel', batch=batch )
            vrun.assertCounts( total=6, npass=6 )

            assert vrun.countGrepLogs( 'option expr false', 'pytest.A=1' ) == 1
            assert vrun.countGrepLogs( 'option expr false', 'shtest.B=1' ) == 1

    def test_using_the_vvtest_system_utilities_in_an_analyze_test(self):
        ""
        platname = util.core_platform_name()

        util.writescript( 'pytest.vvt', """
            #!/usr/bin/env python
            #VVT: parameterize : A = 1 2
            #VVT: analyze : -a
            import sys
            import script_util as vvt
            print3 = vvt.print3
            if '-a' in sys.argv:
                pass
                if vvt.parameter_expr( "not A" ):
                    print3( "analyze param expr true" )
                else:
                    print3( "analyze param expr false" )
                if vvt.platform_expr( 'Junk or """+platname+"""' ):
                    print3( "analyze plat expr true" )
                else:
                    print3( "analyze plat expr false" )
                if vvt.platform_expr( 'Junk' ):
                    print3( "analyze plat expr2 true" )
                else:
                    print3( "analyze plat expr2 false" )
                if vvt.option_expr( 'dbg and not intel' ):
                    print3( "analyze option expr true" )
                else:
                    print3( "analyze option expr false" )
            """ )
        util.writescript( 'shtest.vvt', """
            #!/bin/sh
            #VVT: parameterize : B = 1 2
            #VVT: analyze : -a
            source ./vvtest_util.sh
            analyze=false
            for opt in "$@"
            do
              [ "$opt" = "-a" ] && analyze=true
            done
            if [ $analyze = true ]
            then
                if parameter_expr "B"
                then
                    echo "analyze param expr true"
                else
                    echo "analyze param expr false"
                fi
                if platform_expr 'Junk or """+platname+"""'
                then
                    echo "analyze plat expr true"
                else
                    echo "analyze plat expr false"
                fi
                if platform_expr 'Junk'
                then
                    echo "analyze plat expr2 true"
                else
                    echo "analyze plat expr2 false"
                fi
                if option_expr 'dbg and not intel'
                then
                    echo "analyze option expr true"
                else
                    echo "analyze option expr false"
                fi
            fi
            """ )
        time.sleep(1)

        vrun = util.runvvtest( '-o dbg' )
        vrun.assertCounts( total=6, npass=6 )

        assert vrun.countGrepLogs( 'analyze', '*=*' ) == 0

        assert vrun.countGrepLogs( 'analyze param expr true', 'pytest' ) == 1
        assert vrun.countGrepLogs( 'analyze plat expr true', 'pytest' ) == 1
        assert vrun.countGrepLogs( 'analyze plat expr2 false', 'pytest' ) == 1
        assert vrun.countGrepLogs( 'analyze option expr true', 'pytest' ) == 1

        assert vrun.countGrepLogs( 'analyze param expr false', 'shtest' ) == 1
        assert vrun.countGrepLogs( 'analyze plat expr true', 'shtest' ) == 1
        assert vrun.countGrepLogs( 'analyze plat expr2 false', 'shtest' ) == 1
        assert vrun.countGrepLogs( 'analyze option expr true', 'shtest' ) == 1

    def test_the_runcmd_script_util(self):
        ""
        util.writescript( 'py1.vvt', """
            #!/usr/bin/env python
            import script_util as vvt
            print3 = vvt.print3
            x = vvt.runcmd( 'ls -l' )
            assert x == 0
            """ )
        util.writescript( 'py2.vvt', """
            #!/usr/bin/env python
            import script_util as vvt
            print3 = vvt.print3
            x = vvt.runcmd( 'failprogram', ignore_exit=True )
            assert x != 0
            """ )
        util.writescript( 'py3.vvt', """
            #!/usr/bin/env python
            import script_util as vvt
            print3 = vvt.print3
            vvt.runcmd( 'failprogram' )
            print3( 'should not get here' )
            """ )
        util.writescript( 'py4.vvt', """
            #!/usr/bin/env python
            import script_util as vvt
            print3 = vvt.print3
            out = vvt.runcmd( 'ls -l', capture_output=True )
            print3( out )
            for line in out.split( '\\n' ):
                line = line.rstrip()
                if line and line.split()[-1].endswith( 'vvtest_util.py' ):
                    print3( 'found', line.split()[-1] )
            """ )

        util.writescript( 'helloworld', """
            #!/bin/sh
            echo "hello world"
            """ )
        util.writescript( 'py5.vvt', """
            #!/usr/bin/env python
            #VVT: link : helloworld
            import script_util as vvt
            print3 = vvt.print3
            vvt.runcmd( './helloworld progargs', echo=False )
            """ )

        util.writescript( 'py6.vvt', """
            #!/usr/bin/env python
            #VVT: link : helloworld
            import script_util as vvt
            print3 = vvt.print3
            vvt.runcmd( './helloworld', redirect='prog.out' )
            """ )

        util.writescript( 'hellomars', """
            #!/bin/sh
            echo "hello mars"
            """ )
        util.writescript( 'py7.vvt', """
            #!/usr/bin/env python
            #VVT: link : helloworld hellomars
            import script_util as vvt
            print3 = vvt.print3
            vvt.runcmd( './helloworld', redirect='prog.out' )
            vvt.runcmd( './hellomars', redirect='prog.out' )
            """ )
        util.writescript( 'py8.vvt', """
            #!/usr/bin/env python
            #VVT: link : helloworld hellomars
            import script_util as vvt
            print3 = vvt.print3
            vvt.runcmd( './helloworld', redirect='prog.out' )
            vvt.runcmd( './hellomars', redirect='prog.out', append=True )
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=8, npass=7, fail=1 )

        assert vrun.countGrepLogs( 'vvtest_util.py', 'py1' ) > 0

        assert vrun.countTestLines( 'pass.*py2' ) == 1
        assert vrun.countGrepLogs( 'failprogram', 'py2' ) > 0

        assert vrun.countTestLines( 'pass.*py3' ) == 0
        assert vrun.countGrepLogs( 'command failed*failprogram', 'py3' ) > 0

        assert vrun.countGrepLogs( 'found *vvtest_util.py', 'py4' ) == 1

        assert vrun.countTestLines( 'pass.*py5' ) == 1
        assert vrun.countGrepLogs( 'helloworld*progargs', 'py5' ) == 0

        assert vrun.countGrepLogs( 'hello world', 'py6' ) == 0
        assert len( util.grepfiles( 'hello world',
                                    'TestResults*/py6/prog.out' ) ) == 1

        assert vrun.countGrepLogs( 'hello world', 'py7' ) == 0
        assert vrun.countGrepLogs( 'hello mars', 'py7' ) == 0
        assert len( util.grepfiles( 'hello world',
                                    'TestResults*/py7/prog.out' ) ) == 0
        assert len( util.grepfiles( 'hello mars',
                                    'TestResults*/py7/prog.out' ) ) == 1

        assert len( util.grepfiles( 'hello world',
                                    'TestResults*/py8/prog.out' ) ) == 1
        assert len( util.grepfiles( 'hello mars',
                                    'TestResults*/py8/prog.out' ) ) == 1

    def test_permissions_helpers_in_script_util(self):
        ""
        util.writescript( 'py1.vvt', """
            #!/usr/bin/env python
            from script_util import *
            fp = open( 'script', 'w' )
            fp.write( '#!/bin/sh\\n' )
            fp.write( 'echo "script got executed"\\n' )
            fp.close()
            assert get_permissions( 'script', 'read' )
            assert get_permissions( 'script', 'write' )
            assert not get_permissions( 'script', 'execute' )
            change_permissions( 'script', 'u+x', 'g+x' )
            assert get_permissions( 'script', 'execute' )
            runcmd( './script' )
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=1, npass=1 )

        assert vrun.countGrepLogs( 'script got executed', 'py1' ) == 1

    def test_utilities_catfile_grepfile_prependPATH_which(self):
        ""
        util.writefile( 'file1.txt', """
            this is line one
            and line two
            """ )
        util.writefile( 'file2.txt', """
            the quick brown fox
            jumps over the lazy dog
            """ )
        util.writescript( 'subdir/myscript', """
            #!/bin/sh
            echo "hello from myscript"
            """ )
        util.writescript( 'py1.vvt', """
            #!/usr/bin/env python
            #VVT: link : file1.txt file2.txt
            import os
            from script_util import *
            assert len( grepfile( 'tw[op]', 'file1.txt' ) ) == 1
            catfile( 'file2.txt' )
            prependPATH( os.path.join( SRCDIR, 'subdir' ) )
            print3( 'which =', which( 'myscript' ) )
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=1, npass=1 )

        assert vrun.countGrepLogs( 'quick brown fox', 'py1' ) == 1
        assert vrun.countGrepLogs( 'lazy dog', 'py1' ) == 1
        assert vrun.countGrepLogs( 'which = /*/subdir/myscript', 'py1' ) == 1

    def test_the_user_termination_function(self):
        ""
        util.writescript( 'py1.vvt', """
            #!/usr/bin/env python
            from script_util import *
            def lastcall():
                print3( 'lastcall called' )
            register_termination_function( lastcall )
            try:
                raise Exception( 'fake exception' )
            except:
                pass
            """ )
        util.writescript( 'py2.vvt', """
            #!/usr/bin/env python
            from script_util import *
            def lastcall():
                print3( 'lastcall called' )
            register_termination_function( lastcall )
            raise Exception( 'fake exception' )
            print3( 'should not be here' )
            """ )
        util.writescript( 'py3.vvt', """
            #!/usr/bin/env python
            from script_util import *
            def lastcall():
                print3( 'lastcall called' )
            register_termination_function( lastcall )
            set_have_diff()
            if_diff_exit_diff()
            print3( 'should not be here' )
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=3, npass=1, diff=1, fail=1 )

        assert vrun.countGrepLogs( 'fake exception', 'py1' ) == 0
        assert vrun.countGrepLogs( 'lastcall called', 'py1' ) == 1
        assert vrun.countGrepLogs( 'fake exception', 'py2' ) > 0
        assert vrun.countGrepLogs( 'lastcall called', 'py2' ) == 0
        assert vrun.countGrepLogs( 'should not be here', 'py2' ) == 0
        assert vrun.countGrepLogs( 'exiting diff', 'py3' ) == 1
        assert vrun.countGrepLogs( 'lastcall called', 'py3' ) == 0
        assert vrun.countGrepLogs( 'should not be here', 'py3' ) == 0

    def test_the_python_trace_utility(self):
        ""
        util.writefile( 'file1.txt', """
            this is line one
            and line two
            """ )
        util.writescript( 'py1.vvt', """
            #!/usr/bin/env python
            #VVT: link : file1.txt
            from script_util import *
            def myfunc( ivar=5 ):
                funcvar = 2*ivar
                otherfunc( funcvar )
            def otherfunc( *args ):
                assert len(args) == 1
                print3( 'otherfunc args =', args )
                catfile( 'file1.txt' )
                if 'FOOBAR_NOEXIST_VNAME' in os.environ:
                    print3( 'how could that happen!!' )
            set_python_trace()
            ivar = 4
            myfunc( ivar )
            """ )
        time.sleep(1)

        vrun = util.runvvtest()
        vrun.assertCounts( total=1, npass=1 )

        xlog = glob.glob( 'TestResults*/py1/execute.log' )[0]

        assert len( util.grepfiles(
            'myfunc( *ivar *)*py1.vvt:15', xlog ) ) == 1
        assert len( util.grepfiles(
            'def myfunc( ivar=5 ):*(ivar=4)*py1.vvt:4', xlog ) ) == 1
        assert len( util.grepfiles(
            'def otherfunc( [*]args ):*args=*8*py1.vvt:7', xlog ) ) == 1
        assert len( util.grepfiles( "catfile( 'file1.txt' )", xlog ) ) == 1
        assert len( util.grepfiles( "__contains__", xlog ) ) == 0


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
