#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import glob
import unittest

import testutils as util
from testutils import print3


class test_arguments( unittest.TestCase ):

    def setUp(self):
        util.setup_test()

    def test_use_command_line_option_to_add_test_script_options(self):
        ""
        util.writefile( 'atest.xml', """
            <rtest name="atest">
              <parameterize nx="1 4"/>
              <execute>
                echo "script args $argv"
              </execute>
            </rtest>""" )

        util.writescript( 'btest.vvt', """
            #!/usr/bin/env python
            #VVT: parameterize : planet=earth mars
            import sys
            print ( 'script args '+' '.join( sys.argv[1:] ) )
            """ )
        time.sleep(1)

        self.use_command_line_option_to_add_test_script_options( '' )
        self.use_command_line_option_to_add_test_script_options(
                '--plat '+util.core_platform_name()+' --batch' )

    def use_command_line_option_to_add_test_script_options(self, opt):
        ""
        util.remove_results()

        runr = util.vvtestRunner( opt+' --test-args=--dummy --test-args=foo' )
        assert runr.num_total == 4 and runr.num_pass == 4

        assert len( util.greptestlist(runr.out,'pass.*atest\.nx=1') ) == 1
        assert len( util.greptestlist(runr.out,'pass.*atest\.nx=4') ) == 1
        assert len( util.greptestlist(runr.out,'pass.*btest\.planet=earth') ) == 1
        assert len( util.greptestlist(runr.out,'pass.*btest\.planet=mars') ) == 1

        logL = glob.glob( runr.testdir+'/*test.*/execute.log' )
        assert len(logL) == 4
        for log in logL:
            lineL = util.filegrep( log, 'script args' )
            assert len(lineL) == 1
            assert '--dummy' in lineL[0].split()
            assert 'foo' in lineL[0].split()

        runr = util.vvtestRunner( opt+' -R -p nx=4/planet=earth' + \
                                      ' --test-args=--dummy --test-args=foo',
                                  directory=runr.testdir )
        assert runr.num_total == 2 and runr.num_pass == 2

        assert len( util.greptestlist(runr.out,'pass.*atest\.nx=4') ) == 1
        assert len( util.greptestlist(runr.out,'pass.*btest\.planet=earth') ) == 1

        for log in logL:
            lineL = util.filegrep( log, 'script args' )
            assert len(lineL) == 1
            assert '--dummy' in lineL[0].split()
            assert 'foo' in lineL[0].split()


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
