#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time
import unittest

import testutils as util
from testutils import print3


class The_max_timeout_option( unittest.TestCase ):

    def setUp(self):
        util.setup_test()

    def test_filter_out_tests_based_on_their_timeout(self):
        ""
        util.writescript( 'atest.vvt', """
            #!/usr/bin/env python
            import os, sys, time
            import script_util as vvt
            time.sleep(1)
            """ )
        util.writescript( 'btest.vvt', """
            #!/usr/bin/env python
            import os, sys, time
            import script_util as vvt
            time.sleep(8)
            """ )

        time.sleep(1)

        self.run_filter_out_tests_based_on_their_timeout( '' )
        self.run_filter_out_tests_based_on_their_timeout(
                '--plat '+util.core_platform_name()+' --batch' )

    def run_filter_out_tests_based_on_their_timeout(self, opt):
        ""
        util.remove_results()

        out,np,nd,nf,nn = util.run_vvtest( opt+' -T 30' )
        assert np == 2 and nd == 0 and nf == 0 and nn == 0

        util.remove_results()
        out,np,nd,nf,nn = util.run_vvtest( opt+' --max-timeout 6' )
        assert np == 1 and nd == 0 and nf == 0 and nn == 0
        assert util.numtimeout(out) == 1

        util.remove_results()
        out,np,nd,nf,nn = util.run_vvtest( opt+' -T 30 --max-timeout 6' )
        assert np == 1 and nd == 0 and nf == 0 and nn == 0
        assert util.numtimeout(out) == 1


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
