#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3


class The_max_timeout_option( vtu.vvtestTestCase ):

    def test_filter_out_tests_based_on_their_timeout(self):
        ""
        util.writescript( 'atest.vvt', """
            #!/usr/bin/env python
            import os, sys, time
            import vvtest_util as vvt
            time.sleep(1)
            """ )
        util.writescript( 'btest.vvt', """
            #!/usr/bin/env python
            import os, sys, time
            import vvtest_util as vvt
            time.sleep(8)
            """ )
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( '-T 30', batch=batch )
            vrun.assertCounts( total=2, npass=2 )

            vtu.remove_results()

            vrun = vtu.runvvtest( '--max-timeout 6', batch=batch )
            vrun.assertCounts( total=2, npass=1, timeout=1 )

            vtu.remove_results()

            vrun = vtu.runvvtest( '-T 30 --max-timeout 6', batch=batch )
            vrun.assertCounts( total=2, npass=1, timeout=1 )


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
