#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import time

import vvtestutils as vtu
import testutils as util
from testutils import print3


class Timeout_script_specs( vtu.vvtestTestCase ):

    def test_different_timeout_values(self):
        ""
        platname = vtu.core_platform_name()

        # sleep1 should timeout
        util.writescript( 'sleep1.vvt', """
            #!/bin/sh
            #VVT: timeout : 3
            echo "sleep1 is sleeping 10 seconds"
            sleep 10
            """ )

        # sleep2 should not timeout
        util.writescript( 'sleep2.vvt', """
            #!/bin/sh
            #VVT: timeout : 3
            #VVT: timeout (platforms="""+platname+"""): 0
            echo "sleep2 is sleeping 10 seconds"
            sleep 10
            """ )

        # sleep3 should not timeout
        util.writescript( 'sleep3.vvt', """
            #!/bin/sh
            #VVT: timeout : 3
            #VVT: timeout ( platforms = """+platname+""" ): 15
            echo "sleep3 is sleeping 10 seconds"
            sleep 10
            """ )
        time.sleep(1)

        for batch in [False,True]:

            vtu.remove_results()

            vrun = vtu.runvvtest( batch=batch )
            vrun.assertCounts( total=3, npass=2, timeout=1 )

            vrun = vtu.runvvtest( '-wT 1.5', batch=batch )
            vrun.assertCounts( total=3, timeout=3 )

            vrun = vtu.runvvtest( '-wT 20', batch=batch )
            vrun.assertCounts( total=3, npass=3 )


########################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
