#!/usr/bin/env python

# Copyright 2018 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.

#RUNTEST:

import sys
sys.dont_write_bytecode = True
sys.excepthook = sys.__excepthook__
import os
import unittest
import time

try:
    from StringIO import StringIO
except:
    from io import StringIO

import testutils as util
from testutils import print3

import batchitf as bat


class Function_parse_variant( unittest.TestCase ):

    def setUp(self):
        ""
        util.setup_test( cleanout=False )

    def test_empty(self):
        ""
        D = bat.parse_variant( '' )
        assert len(D) == 0

    def test_single_key_value(self):
        ""
        D = bat.parse_variant( 'key=value' )
        assert len(D) == 1
        assert D['key'] == 'value'

        D = bat.parse_variant( 'key=2' )
        assert len(D) == 1
        assert D['key'] == '2'

    def test_multiple_key_value(self):
        ""
        D = bat.parse_variant( 'key=value foo=2 bar=1.2' )
        assert len(D) == 3
        assert D['key'] == 'value'
        assert D['foo'] == '2'
        assert D['bar'] == '1.2'


class Function_lineprint( unittest.TestCase ):

    def setUp(self):
        ""
        util.setup_test( cleanout=False )

    def test_empty_print(self):
        ""
        sio = StringIO()
        bat.lineprint( sio )
        assert len( sio.getvalue() ) == 0

    def test_print_empty_string(self):
        ""
        sio = StringIO()
        bat.lineprint( sio, '' )
        assert sio.getvalue() == '\n'

    def test_print_some_lines(self):
        ""
        sio = StringIO()
        bat.lineprint( sio, 'line one', 'line two' )
        assert sio.getvalue() == 'line one\nline two\n'


class Function_compute_num_nodes( unittest.TestCase ):

    def setUp(self):
        ""
        util.setup_test( cleanout=False )

    def test_platform_ppn_is_one(self):
        ""
        assert bat.compute_num_nodes( 0, None, 1 ) == 1
        assert bat.compute_num_nodes( 1, None, 1 ) == 1
        assert bat.compute_num_nodes( 2, None, 1 ) == 2

    def test_platform_ppn_is_two(self):
        ""
        assert bat.compute_num_nodes( 0, None, 2 ) == 1
        assert bat.compute_num_nodes( 1, None, 2 ) == 1
        assert bat.compute_num_nodes( 2, None, 2 ) == 1
        assert bat.compute_num_nodes( 3, None, 2 ) == 2
        assert bat.compute_num_nodes( 4, None, 2 ) == 2
        assert bat.compute_num_nodes( 5, None, 2 ) == 3

    def test_requested_cores_per_node_equals_one(self):
        ""
        assert bat.compute_num_nodes( 1, 1, 8 ) == 1
        assert bat.compute_num_nodes( 2, 1, 8 ) == 2
        assert bat.compute_num_nodes( 0, 1, 8 ) == 1

    def test_requested_cores_per_node_equals_two(self):
        ""
        assert bat.compute_num_nodes( 0, 2, 8 ) == 1
        assert bat.compute_num_nodes( 1, 2, 8 ) == 1
        assert bat.compute_num_nodes( 2, 2, 8 ) == 1
        assert bat.compute_num_nodes( 3, 2, 8 ) == 2
        assert bat.compute_num_nodes( 4, 2, 8 ) == 2
        assert bat.compute_num_nodes( 5, 2, 8 ) == 3

    def test_platform_ppn_is_None(self):
        ""
        assert bat.compute_num_nodes( 0, 2, None ) == 1
        assert bat.compute_num_nodes( 1, 2, None ) == 1
        assert bat.compute_num_nodes( 2, 2, None ) == 1
        assert bat.compute_num_nodes( 3, 2, None ) == 2

        assert bat.compute_num_nodes( 0, None, None ) == 1
        assert bat.compute_num_nodes( 1, None, None ) == 1
        assert bat.compute_num_nodes( 2, None, None ) == 1
        assert bat.compute_num_nodes( 3, None, None ) == 1


class Function_format_time_to_HMS( unittest.TestCase ):

    def setUp(self):
        ""
        util.setup_test( cleanout=False )

    def test_string_with_a_colon_is_returned_unchanged(self):
        ""
        hms = bat.format_time_to_HMS( '0:01' )
        assert hms == '0:01'

    def test_string_without_a_colon_is_converted_to_seconds(self):
        ""
        hms = bat.format_time_to_HMS( '66' )
        assert hms == '0:01:06'

    def test_less_than_a_minute(self):
        ""
        hms = bat.format_time_to_HMS( '59' )
        assert hms == '0:00:59'

        hms = bat.format_time_to_HMS( '09' )
        assert hms == '0:00:09'

        hms = bat.format_time_to_HMS( 9 )
        assert hms == '0:00:09'

        hms = bat.format_time_to_HMS( 0 )
        assert hms == '0:00:00'

    def test_less_than_an_hour(self):
        ""
        hms = bat.format_time_to_HMS( 5*60 )
        assert hms == '0:05:00'

        hms = bat.format_time_to_HMS( 5*60+34 )
        assert hms == '0:05:34'

        hms = bat.format_time_to_HMS( 59*60+59 )
        assert hms == '0:59:59'

    def test_less_than_a_day(self):
        ""
        hms = bat.format_time_to_HMS( 60*60+1 )
        assert hms == '1:00:01'

        hms = bat.format_time_to_HMS( 60*60+11*60 )
        assert hms == '1:11:00'

        hms = bat.format_time_to_HMS( 60*60+11*60+11 )
        assert hms == '1:11:11'

    def test_more_than_a_day(self):
        ""
        hms = bat.format_time_to_HMS( 25*60*60+60 )
        assert hms == '25:01:00'

        hms = bat.format_time_to_HMS( 25*60*60+6 )
        assert hms == '25:00:06'

        hms = bat.format_time_to_HMS( 25*60*60+6*60+6 )
        assert hms == '25:06:06'


class Function_parse_date_string( unittest.TestCase ):

    def setUp(self):
        ""
        util.setup_test( cleanout=False )

    def test_invalid_form(self):
        ""
        tm = bat.parse_date_string( 'foo bar' )
        assert tm == None

    def test_RHEL6_date_format(self):
        ""
        tm = bat.parse_date_string( 'Sun Mar  4 10:29:22 MST 2018' )
        assert abs( tm - 1520184562 ) < 2

        tm = bat.parse_date_string( 'Wed Jul  4 10:29:22 MDT 2018' )
        assert abs( tm - 1530721762 ) < 2


############################################################################

util.run_test_cases( sys.argv, sys.modules[__name__] )
